---
output: 
  pdf_document:
    citation_package: natbib
    keep_tex: true
    fig_caption: true
    latex_engine: pdflatex
    template: ./svm-latex-ms.tex
title: "The Role of Machine Learning in Econometrics"
author: Nathan Eskelson
- name: Nathan Eskelson
  affiliation: Jon M. Huntsman School of Business
abstract: "In this article I will discuss the role and value of modern business analytics as a 'disequilibrium' set of technologies. Business Analytics is made up three working parts: Economics, Statistics, and Computer Science. The focus of this paper will be how computer science can more efficiently combine these two, allowing companies to have an advantage. First, we will look at the disequilibrium theory and discuss what is meant by disequilibrium. We will then begin to dive into the types of business analytics that are currently being used to give companies the advantage in a disequilibrium market. We will begin by looking at machine learning as well as reinforcement learning and what that data does in econometrics. We will also take a look at Artificial Intelligence (AI) and other forms of business analytics. In conclusion, it can be determined that the value of date and machine learning is important in econometrics and the business world. With it, this is how companies give themselves an advantage in a market of disequilibrium. It's not about having the most data, it's about having the best data and knowing what to do with it."
keywords: "machine learning, reinforcement learning, ML, RL, econometrics"
date: "`r format(Sys.time(), '%B %d, %Y')`"
geometry: margin=1in
fontfamily: mathpazo
fontsize: 11pt
spacing: double
bibliography: ./master.bib
biblio-style: apsr
---


>  

# Introduction

I agree with Buchanon when he said, "Economists should be 'market economists,'' but only because I think they should concentrate on market or exchange institutions, again recalling that these are to be conceived in the widest possible sense. This need not bias or prejudice them for or
against any particular form of social order. Learning more about how markets work means learning more about how markets work. They may work better or worse, in terms of whatever criteria that might be imposed, than uninformed opinion leads one to expect." This paper is going to be used to focus more on what economists should be doing more of in the current day, which is applying business analytics. Business analytics refers to the skills, technologies, practices for continuous iterative exploration and investigation of past business performance to gain insight and drive business planning. @wiki:businessanalytics Analytics are used to drive decision making within a business as well as planning as stated by Wikipedia. There are many different forms of business analytics that are used in the modern day in order to give companies an advantage over their competitors. A few of the different types that we will be looking at in this paper are behavorial analytics, machine learning, and reinforcement learning. The focus will be to show how they are used and how they can lead to an advantage for a company. The only reason this would be possible to have an advantage is if the market was not in equilibrium. We will begin by looking at what a market in disequilibrium means and how that affects econometrics. 

## Subsection 1

The problem is precisely
how to extend the span of our utilization of resources beyond
the span of the control of any one mind; and, therefore, how to dispense
with the need of conscious control and how to provide inducements
which will make the individuals do the desirable things without anyone
having to tell them what to do.

In order for a business to have the opportunity to gain an advantage against their competitor, there needs to exist disequilibrium in the market. A Theory of the Market Process defines equilibrium as "a state where no economic agents have an incentive to change their behavior. Such a state can occur only when there remain no unexploited profit opportunities." @thomsen2002theory Almost all markets have opportunities that haven't been discovered or utilized to their maximum. Franklin Fisher, an equilibrium economist, said "It is a mistake to ground disequilibrium theory in the equilibrium behavior of agents. Rather, the theory of the household and the firm must be reformulated and extended where necessary to allow agents to perceive that the economy is not in equilibrium and to act on that perception. Without this, we cannot hope to provide a theory of what happens when arbitrage opportunities appear, for the essence of the appearance of such opportunities is that agents see and act on them." An agent is an actor or a decision maker in some aspect of the economy. 

Buchanon states in his paper, "What Should Economists Do?". "A market is not competitive by assumption or by construction. A market becomes competitive, and competitive rules come to be established as institutions emerge to place limits on individual behavior patterns. It is this becoming process, brought about by the continuous pressure of human behavior in exchange, that is the central part of our discipline, if we have one, not the dry-rot of postulated perfection." This is where behavioral analytics, a form of business analytics, comes into play. Behavioral analytics is gathering data on not only where people visit or click online, but the process they go through to arrive at their desired destination. Seeing how a user got to the final destination is something that can help them learn more about the user and what kind of user it is. It could be someone that came from an email link, a VIP user, or any other kind of user that they track and have data on. This will allow them to effectively target the segment. This allows the company to learn about how they could better the process and make it even easier for the user to get what they need to done. 

Constantly gathering data for just one website could be exhausting for people to decipher. There is a lot of labor that goes into this where we could be involving computers more to ease the process. Hayek said in his paper, "The Use of Knowledge in Society", "The problem is precisely how to extend the span of our utilization of resources beyond the span of the control of any one mind; and, therefore, how to dispense with the need of conscious control and how to provide inducements which will make the individuals do the desirable things without anyone having to tell them what to do." Business analytics is applying this and expanding our use of resources. We are in a technology filled world now, let's learn how to better use that and make our process more efficient. For that reason we begin to look at what machine learning is capable of and how it is helping companies.


## Subsection 2 

Machine learning is the next step to gaining an advantage on your competitors. As described at the beginning of this paper, business analytics is used to gain insight and drive business planning. Matt Taddy said, "Machine learning can automate and accelerate tasks in applied econometrics workflows." @taddy2017 He goes on to explain in his video as well that what is currently being asked of economists is standard economic questions at a ridiculous scale. The weight of the data and the difficulty is pushing everything else out of the way. That is why the labor market was in such a need because the process wasn't being done to the most efficient opportunity. With machine learning it allows the companies to do the job in a more efficient way and not needing more bodies just to do something a computer would be able to do.

How does machine learning work? Machine learning allows us to take data and prepare a model that can make predictions on what comes next. The perfect example of machine learning is the Google search engine. It takes our interests and past searches and begins to predict what we are searching for. If I am constantly searching for sports or more specifically the Utah Jazz, when I begin to type Utah, it will populate with many suggestions for searches surrounding the Utah Jazz. So, the first thing we need for machine learning is data. It needs a lot of data to begin to calculate all of the results from the previous data. Once we have the data we need to be able to go through "training". After we have selected a model of our choice, training allows us to teach the data what the answer should be given the data we receive. This takes a lot of time and cycles in order to get the data to predict the right answer. In the beginning, we put random values in the variables and see what the outcome would be, then we compare this to the actual outcome. We continue to adjust what we need to in order to get the proper output. It can never be expected for the machine to always be 100% correct. However, we can continue to adjust it in order to make the best prediction and be right most of the time. 

Once we have our model working, we can continue to evaluate it but we expect the model to be able to learn from itself without being explicitly programmed. In the ecommerce setting, websites are learning by the behavior of the user and making browsing that much easier and quick. Online shopping continues to grow so this is important to companies within the industry. Another thing that machine learning is capable of doing is forecasting. Companies like Walmart gathers data and then are able to forecast their sales, when they will be busy and what kind of products they need to order when they are popular. Machine learning is becoming the new norm with businesses having all sorts of data. ML is not designed to replace economists or create economic insights, it is to speed up the labor-intense measurement. 

# Middle Section

To delve even deeper into machine learning, we will begin to look at reinforcement learning. Reinforcement learning is a form of machine learning. Reinforcement learning is when the machine is correct, it is rewarded. If not, it re-analyzes and then tries again until it is right. It is like walking, it takes time and time again for a child to walk with many failed attempts in there. When it fails, it learns from the fall and tries again. When it is successful, it is rewarded. The same goes for reinforcement learning. I really like the definition that Wikipedia has for RL, "Reinforcement learning is an area of machine learning concerned with how software agents ought to take actions in an environment so as to maximize some notion of cumulative reward." @wiki:reinforcementlearning This refers back to our agents that were talked about above in this paper. It maximizes the reward. 

As we allow for agents to understand that they are in disequilibrium this is one thing they should look to use in order to 

# Summary and Conclusion

In conclusion, we can see that data analytics in all forms allows a company to gain a competitive advantage in a world of disequilibrium. Companies such as Google, Amazon, Spotify and Facebook are all examples that have used data analytics to continue to grow their advantage against their competitors. It is not only by the searches and purchases that the users make. It has allowed them to better understand and market each segment of their users and make their experience even better. This is where machine learning and artificial intelligence come in, it has allowed these companies to thrive in the competition and stand atop the hierarchy of each of their industries. These are just the businesses that you would recognize, there are many other up and coming businesses that are learning and hiring to better their process and become more competitive. Machine learning allows companies to work smarter and not harder. It takes away the stress of having to hire a lot of people and makes it even easier and efficient. In the end, if you believe that the market you belong to is in equilibrium, all of your competitors are currently trying to find where it is not and exploit it. Business analytics is the way of the future and rapidly becoming part of the present. It's best to get started now before you fall behind your competitor. 

<!--
# References
\setlength{\parindent}{-0.2in}
\setlength{\leftskip}{0.2in}
\setlength{\parskip}{8pt}
\vspace*{-0.2in}
\noindent
-->

